// Renders an array of company records into portals.yml content.
// Includes the tracked_companies block, the 4 Korean job boards,
// and a title_filter tuned to backend/infra/cloud keywords.

export function renderPortalsYml(companies) {
  const companiesBlock = companies
    .map(c => `  - name: ${c.name}
    slug: ${c.slug}
    careers_url: "${c.url}"
    tags: [${c.stack.join(', ')}]`)
    .join('\n');

  return `# Portal Scanner Configuration (한국 시장)
# Generated by scripts/seed-from-obsidian.mjs.
# Edit freely — never auto-updated.

# -- Title filter --
title_filter:
  positive:
    - "Backend"
    - "Server"
    - "Platform"
    - "Infra"
    - "Infrastructure"
    - "DevOps"
    - "SRE"
    - "Cloud"
    - "Kubernetes"
    - "백엔드"
    - "서버"
    - "플랫폼"
    - "인프라"
    - "클라우드"
  negative:
    - "Frontend"
    - "iOS"
    - "Android"
    - "Game"
    - "게임"
    - "Junior"
    - "Intern"
    - "인턴"
    - "Data Scientist"
    - "ML Engineer"
  seniority_boost:
    - "Senior"
    - "Lead"
    - "Staff"
    - "시니어"

# -- Tracked companies (seeded from /Users/2302-pc04/space/docs/02_Areas/기업/) --
tracked_companies:
${companiesBlock}

# -- Korean job boards --
boards:
  - name: 원티드
    url: https://www.wanted.co.kr/search?query=backend
    type: aggregator
    enabled: true
  - name: 점핏
    url: https://jumpit.saramin.co.kr
    type: aggregator
    enabled: true
  - name: 지킹
    url: https://zighang.com/recruitment
    type: aggregator
    enabled: true
  - name: 인디스워크
    url: https://inthiswork.com/it
    type: aggregator
    enabled: true

# Note: Korean job boards are JS-rendered. Use Playwright (already a dependency)
# in scan mode. First run may need selector adjustments per board.
`;
}
